name: macOS C++20 Modules CI

on:
  workflow_dispatch:
  
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: System Diagnostics
      run: |
        uname -a
        sw_vers
        mdfind 'kMDItemFSName == "clang"c'
        clang -v

    - name: Install Xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest

    - name: Build Project
      run: |
        xmake f -c -p iphoneos
        xmake -rv
        
        xmake f -c
        xmake -rv

        xmake run


