name: BSD & Unix Multi-Arch Build

on:
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]
  workflow_dispatch:

jobs:
# --- Solaris (OpenIndiana) ---
  solaris:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Test on Solaris (x86_64)
        uses: vmactions/openindiana-vm@v1
        with:
          usesh: true
          prepare: |
            pkg refresh
            pkg install gcc-14
            pkg install developer/clang-21
          run: |
            uname -a
            gcc -v
            clang -v

            echo | gcc -E -dM -
            echo now clang
            echo | clang -E -dM -
            
            gcc -m64 -ffreestanding -fno-exceptions -fno-rtti -fno-stack-protector -nostdlib -nostartfiles -static -o hello main.cpp
            clang -m64 -ffreestanding -fno-exceptions -fno-rtti -fno-stack-protector -nostdlib -nostartfiles -static -o hello1 main.cpp
            ./hello
            ./hello1
