name: MIPS

on:
  workflow_dispatch:

jobs:
  cross-mips:
    runs-on: ubuntu-latest
    container:
      image: debian:sid

    steps:
      - uses: actions/checkout@v7

      - name: Install cross-compiler
        run: |
          apt-get update
          apt-get install -y g++-16-mips64el-linux-gnuabi64

      - name: Compile code
        run: |
          mips64el-linux-gnuabi64-g++-16 -v -O2 -Wall -Wextra -Wpedantic \
            -ffreestanding -fno-exceptions -fno-rtti -fno-threadsafe-statics \
            -fno-use-cxa-atexit -fno-stack-protector -fno-pic -fno-pie \
            -fno-unwind-tables -fno-asynchronous-unwind-tables -nostdlib \
            -nostartfiles -nodefaultlibs -static -no-pie -Wl,-e,_start \
            -Wl,--build-id=none hello.cpp -o hello

      - name: Upload binary artifact
        uses: actions/upload-artifact@v7
        with:
          name: mips-binary
          path: hello

  run-in-container:
    needs: cross-mips
    runs-on: ubuntu-latest

    steps:
      - name: Download binary artifact
        uses: actions/download-artifact@v7
        with:
          name: mips-binary

      - name: Make executable and run inside container
        run: |
          chmod +x ./hello
          docker run --rm -v "$PWD":/work -w /work ghcr.io/alextwothousand/debian-mips64el:bookworm ./hello
