name: Xcode 27

on:
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]
  workflow_dispatch:

jobs:
  solaris:
    runs-on: xcode-27
    steps:
      - name: Build
        run: |
          uname -a
          sw_vers
          clang -v
